controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
vue:
    path: /{views}
    controller: App\Controller\HomeController::index
    requirements:
        views: .*